### ISSUE TITLE
Toggle Bags button

### ISSUE THREAD

**Issue by trinnah** [Benik/ElvUI_BenikUI#15]
Minor bug I've discovered, "toggle bags" button seems to be broken! It just does NOTHING unless I disable Benik. Not a super big issue because I'm not equipping bags all the time but it is a minor annoyance when that does come up.

Tested with only ElvUI & config then with just those two and BenikUI, it definitely only happens with Benik enabled.

(Oh and I wanted to say thank you SOOOO much for the option to disable those art bars. ;3)

**Comment by Merathilis** [comment]
hm...i don't have this issue. I must say i play with Pixel Perfect disable, maybe it's a Pixel Perfect thingy :D

**Comment by trinnah** [comment]
Tested again with only BenikUI, ElvUI & ElvUI config, with and without pixel perfect. Still nada. With just ElvUI & config it works fine (with and without pixel perfect. (: )

**Comment by Merathilis** [comment]
strange, then we need to wait Benik come around here ;) 

P.S. i figuered it out: If you disable the BenikUI Style, then this Bug exist with BenikUI Style enable everything it's okay

**Comment by trinnah** [comment]
Ah good call! Just tested that, that's what it is. I have Benik's style disabled! I re-enabled it and it works fine.

**Comment by Benik** [comment]
Thank you guys for grabbing this :)
