### ISSUE TITLE
Lua Error with latest commit

### ISSUE THREAD

**Issue by Merathilis** [Benik/ElvUI_BenikUI#18]
hi,

with your latest commit i get the following LUA Error:

1x ...eElvUI_BenikUI\modules\dashboard\options.lua:371: attempt to index local 't' (a nil value)
...eElvUI_BenikUI\modules\dashboard\options.lua:371: in function `member'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-99.lua:249: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:197>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-99.lua:1326: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1055>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-99.lua:1588: in function `FeedGroup'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-99.lua:1513: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1493>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...aceAddOnSkins\Libs\AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...Libs\AceGUI-3.0-34\widgets\AceGUIContainer-TabGroup.lua:156: in function `SelectTab'
...Libs\AceGUI-3.0-34\widgets\AceGUIContainer-TabGroup.lua:67: in function <...Libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:64>

Locals:
nil

**Comment by Benik** [comment]
Forgot to commit the defaults. Should be fixed now. Thanks :)
