### ISSUE TITLE
Wow token auction frame lua Error

### ISSUE THREAD

**Issue by Merathilis** [Benik/ElvUI_BenikUI#24]
hi ;)

get the following LUA Error:

1x ElvUI_BenikUI\modules\skins\skins.lua:205: attempt to index field 'backdrop' (a nil value)
ElvUI_BenikUI\modules\skins\skins.lua:205: in function `?'
...vUI\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:147: in function <...vUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...vUI\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:92: in function `Fire'
...faceElvUI\libs\AceEvent-3.0\AceEvent-3.0-3.lua:120: in function <...faceElvUI\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: ?
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:336: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:347: in function `AuctionFrame_LoadUI'
FrameXML\UIParent.lua:1328: in function <FrameXML\UIParent.lua:814>

Locals:
nil

**Comment by Benik** [comment]
Hope it's fixed now (although I've added the wrong comment #) :dancers:

**Comment by Merathilis** [comment]
we will see ;)
