### ISSUE TITLE
Exprepbar Lua Error

### ISSUE THREAD

**Issue by Merathilis** [Benik/ElvUI_BenikUI#30]
hi :)

since today, i get the following LUA Error when get Rep. in a Timewalking Dungeon:

17x ...faceElvUI_BenikUI\modules\misc\exprepbar.lua:200: bad argument #5 to 'format' (string expected, got nil)
[C]: in function `format'
...faceElvUI_BenikUI\modules\misc\exprepbar.lua:200: in function `UpdateReputation'
...faceElvUI_BenikUI\modules\misc\exprepbar.lua:63: in function <...faceElvUI_BenikUI\modules\misc\exprepbar.lua:61>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @ElvUI\libs\AceAddon-3.0\AceAddon-3.0.lua:398
 Enable = <function> defined @ElvUI\libs\AceAddon-3.0\AceAddon-3.0.lua:325
 NewModule = <function> defined @ElvUI\libs\AceAddon-3.0\AceAddon-3.0.lua:266
 EnableModule = <function> defined @ElvUI\libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 GetModule = <function> defined @ElvUI\libs\AceAddon-3.0\AceAddon-3.0.lua:241
 IterateEmbeds = <function> defined @ElvUI\libs\AceAddon-3.0\AceAddon-3.0.lua:473
 SecureHookScript = <function> defined @ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:410
 defaultModuleLibraries = <table> {
 }
 EnableDisable_ExperienceBar = <function> defined @ElvUI_BenikUI\modules\misc\exprepbar.lua:210
 RawHookScript = <function> defined @ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:395
 xpbar = <unnamed> {
 }
 ChangeXPcolor = <function> defined @ElvUI_BenikUI\modules\misc\exprepbar.lua:421
 GetName = <function> defined @ElvUI\libs\AceAddon-3.0\AceAddon-3.0.lua:310
 baseName = "ElvUI_BenikUI"
 name = "ElvUI_BUIExpRep"
 Initialize = <function> defined @ElvUI_BenikUI\modules\misc\exprepbar.lua:483
 IsEnabled = <function> defined @ElvUI\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 orderedModules = <table> {
 }
 repbar = <unnamed> {
 }
 DisableModule = <function> defined @ElvUI\libs\AceAddon-3.0\AceAddon-3.0.lua:381
 ChangeRepColor = <function> defined @ElvUI_BenikUI\modules\misc\exprepbar.lua:446
 LoadBars = <function> defined @ElvUI_BenikUI\modules\misc\exprepbar.lua:390
 ApplyXpRepStyling = <function> defined @ElvUI_BenikUI\modules\misc\exprepbar.lua:344
 UpdateExperience = <function> defined @ElvUI_BenikUI\modules\misc\exprepbar.lua:112
 RegisterMessage = <function> defined @ElvUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 HookScript = <function> defined @ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:366
 ChangeRepXpFont = <function> defined @ElvUI_BenikUI\modules\misc\exprepbar.lua:228
 EnableDisable_ReputationBar = <function> defined @ElvUI_BenikUI\modules\misc\exprepbar.lua:219
 IsHooked = <function> defined @ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:493
 UpdateReputation = <function> defined @ElvUI_BenikUI\modules\misc\exprepbar.lua:162
 GetXP = <function> defined @ElvUI_BenikUI\modules\misc\exprepbar.lua:104
 IsModule = <function> defined @ElvUI\libs\AceAddon-3.0\AceAddon-3.0.lua:248
 defaultModuleState = true
 SetDefaultModuleState = <function> defined @ElvUI\libs\AceAddon-3.0\AceAddon-3.0.lua:418
 UnregisterAllEvents = <function> defined @ElvUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
 SendMessage = <function> defined @ElvUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:87
 SetEnabledState = <function> defined @ElvUI\libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 UnregisterMessage = <function> defined @ElvUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
 RegisterEvent = <function> defined @ElvUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 UnregisterAllMessages = <function> defined @ElvUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
 hooks = <table> {
 }
 SetDefaultModulePrototype = <function> defined @ElvUI\libs\AceAddon-3.0\AceAddon-3.0.lua:440
 SecureHook = <function> defined @ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:336
 IterateModules = <function> defined @ElvUI\libs\AceAddon-3.0\AceAddon-3.0.lua:468
 UnhookAll = <function> defined @AddO

**Comment by Benik** [comment]
Please try if this fixes shit :P
